# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-26 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20171126_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='desc',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
